### ISSUE TITLE
Location of tutorial example dataset

### ISSUE THREAD

**Issue by GenevieveBuckley** [lens-biophotonics/ZetaStitcher#1]
Where can I download the example dataset that's referenced on the Zetastitcher [tutorial](https://lens-biophotonics.github.io/ZetaStitcher/tutorial.html#tutorial) page? There's no information about this on the current docs page.

**Comment by gmazzamuto** [comment]
Hi, can you send me an email to mazzamuto@lens.unifi.it? I'll be glad to provide an example dataset.
