### ISSUE TITLE
Get tile position in new coordinate space

### ISSUE THREAD

**Issue by MathieuBo** [lens-biophotonics/ZetaStitcher#15]
Hello, 

I was wondering if I can access the final tile position after the stitching happened. 
Essentially, I have data from other modalities stored as one numpy matrix per tile and would like to stitch these matrices together. 
The stitch.yml file contains Xs and Ys coordinates which seems to be what I need. What exactly do they correspond to?

Thanks!
Mathieu

**Comment by gmazzamuto** [comment]
Hi Mathieu,

Yes, that's correct, `Xs` and `Ys` correspond to the stitched coordinates. In the final volume, the coordinates of the tile in the top-left corner are all zero: `(Xs, Ys, Zs) = (0, 0, 0)`. For each tile, `(Xs, Ys, Zs)` are the coordinates of the top-left corner of the tile in the final volume, measured from the top-left corner of the final volume.

If you need to access the coordinates programmatically, you can do like this:
```py
from zetastitcher import FileMatrix

fm = FileMatrix('stitch.yml')

fm.data_frame[['Xs', 'Ys', 'Zs']]
```

Hope this helps! Just let me know if you need more info

Cheers,
Giacomo

**Comment by MathieuBo** [comment]
This is fantastic thanks a lot!

**Comment by MathieuBo** [comment]
This is fantastic, thanks a lot!
